import type { Creative } from "./types";

export function generateFallbackCreatives(
  clinicType: string,
  service: string,
  location: string,
  offerDetails: string
): Creative[] {
  const offer = offerDetails || "limited-time special offer";
  return [
    {
      id: 1,
      avatar: "Busy Professional",
      emotion: "frustration",
      style: "Pattern Interrupt",
      headline: `Stop Wasting Time On ${service} That Don't Work`,
      primary_text: `You've tried everything. You've spent hours researching ${service} options in ${location}, only to end up more confused than before. Your time is too valuable for that. Our ${clinicType} specializes in getting you real results fast — so you can get back to what matters most. ${offer}. Book your spot today.`,
      image_prompt: `Professional woman in her 40s looking relieved and confident after a ${service} treatment, modern ${clinicType} interior, soft natural lighting, warm tones, shot from slightly below eye level, lifestyle photography style`,
      hook: `Tired of ${service} that disappoint?`,
      category: "Avatar Test A",
    },
    {
      id: 2,
      avatar: "Busy Professional",
      emotion: "empowerment",
      style: "Direct Offer",
      headline: `${location}'s Best-Kept ${service} Secret`,
      primary_text: `Smart professionals in ${location} already know about us. They come to our ${clinicType} because they want results — not gimmicks. You deserve to look and feel your absolute best without wasting a single minute. ${offer}. Your transformation starts with one simple step.`,
      image_prompt: `Confident business professional smiling after treatment at modern ${clinicType}, clean bright environment, professional headshot style, neutral background, studio lighting`,
      hook: `${location} professionals already know this`,
      category: "Avatar Test A",
    },
    {
      id: 3,
      avatar: "Aging Gracefully Seeker",
      emotion: "hope",
      style: "Before/After",
      headline: `What If ${service} Could Turn Back Time?`,
      primary_text: `Every day you look in the mirror and wonder what happened. The good news? You don't have to settle for how things are. Our ${clinicType} in ${location} has helped hundreds of people just like you rediscover their confidence with ${service}. ${offer}. Your best days are still ahead.`,
      image_prompt: `Split image showing subtle before and after of ${service} results, elegant mature person, soft diffused lighting, clean composition, ${clinicType} setting`,
      hook: "Your mirror doesn't tell the full story",
      category: "Avatar Test A",
    },
    {
      id: 4,
      avatar: "Aging Gracefully Seeker",
      emotion: "trust",
      style: "Testimonial",
      headline: `"I Wish I Found This ${clinicType} Sooner"`,
      primary_text: `That's what our patients say after their first ${service} session. You want a provider you can trust — someone who listens, understands, and delivers. At our ${clinicType} in ${location}, your comfort comes first. ${offer}. See why hundreds of patients rate us 5 stars.`,
      image_prompt: `Warm candid photo of happy patient at ${clinicType}, genuine smile, soft background blur, warm golden lighting, authentic lifestyle photography`,
      hook: "What 500+ patients already know",
      category: "Avatar Test A",
    },
    {
      id: 5,
      avatar: "New Mom",
      emotion: "empowerment",
      style: "Native Social",
      headline: `Mama, You Deserve This ${service} Glow-Up`,
      primary_text: `You've given so much to everyone else. Your body changed. Your confidence dipped. But here's the truth — you deserve to feel like YOU again. Our ${clinicType} in ${location} specializes in helping moms reclaim their confidence with ${service}. ${offer}. This is your time.`,
      image_prompt: `Young mother looking radiant and confident, casual lifestyle setting, bright airy photography, natural window light, ${clinicType} spa atmosphere`,
      hook: "This is YOUR glow-up moment",
      category: "Avatar Test B",
    },
    {
      id: 6,
      avatar: "New Mom",
      emotion: "curiosity",
      style: "Educational",
      headline: `The Truth About ${service} Nobody Tells New Moms`,
      primary_text: `You've heard the myths. You've read the scary articles. But the reality of ${service} at a trusted ${clinicType} is completely different from what you've been told. We break down exactly what to expect — no surprises, no pressure. Just honest answers. ${offer}. Learn the facts today.`,
      image_prompt: `Educational infographic style, clean modern design, ${clinicType} branded content, minimalist layout, soft emerald and white color scheme`,
      hook: "3 myths about ${service} debunked",
      category: "Avatar Test B",
    },
    {
      id: 7,
      avatar: "Health-Conscious Executive",
      emotion: "envy",
      style: "Social Proof",
      headline: `Why ${location} Executives Choose Our ${service}`,
      primary_text: `Your colleagues look amazing. Your competitors radiate confidence. What's their secret? Many of them quietly visit our ${clinicType} for ${service}. No one needs to know — the results speak for themselves. ${offer}. Join the executives who invest in themselves.`,
      image_prompt: `Executive boardroom or luxury lounge setting, confident professional, tailored clothing, power pose, warm dramatic lighting, editorial magazine style`,
      hook: "Your competition's unfair advantage",
      category: "Avatar Test B",
    },
    {
      id: 8,
      avatar: "Health-Conscious Executive",
      emotion: "urgency",
      style: "Direct Offer",
      headline: `This Week Only: ${service} At Our ${clinicType}`,
      primary_text: `You've been thinking about it for months. You know you want to try ${service}. This is your sign. Our ${clinicType} in ${location} is offering an exclusive deal this week only. ${offer}. Spots are filling fast — don't let this one slip away.`,
      image_prompt: `Urgent promotional style, bold clean typography overlay, ${clinicType} luxury interior, countdown timer visual element, vibrant emerald accent colors`,
      hook: "Only 5 spots left this week",
      category: "Emotion Test",
    },
    {
      id: 9,
      avatar: "Social Media Millennial",
      emotion: "envy",
      style: "Native Social",
      headline: `POV: You Finally Tried ${service} In ${location}`,
      primary_text: `Your friends are going to ask what changed. Your selfie game is about to hit different. ${service} at our ${clinicType} is the upgrade you didn't know you needed. Real results. Zero downtime. Maximum confidence. ${offer}. Tag a friend who needs this.`,
      image_prompt: `Instagram-style lifestyle photo, young person taking selfie showing ${service} results, trendy background, ring light glow, social media aesthetic, vibrant colors`,
      hook: "POV: Your glow-up just arrived",
      category: "Avatar Test B",
    },
    {
      id: 10,
      avatar: "Social Media Millennial",
      emotion: "curiosity",
      style: "Pattern Interrupt",
      headline: `I Tried ${service} So You Don't Have To`,
      primary_text: `Okay but seriously — is ${service} worth the hype? I went to a ${clinicType} in ${location} and here's what actually happened. No filter. No BS. Just my honest experience. Spoiler: I'm already booking my next session. ${offer}. See for yourself.`,
      image_prompt: `Casual vlog-style photo, authentic unfiltered look, modern ${clinicType} in background, natural lighting, iPhone photography aesthetic, raw and real`,
      hook: "Honest review: Is it worth it?",
      category: "Style Test",
    },
    {
      id: 11,
      avatar: "Budget-Conscious Seeker",
      emotion: "fear",
      style: "Breaking News",
      headline: `${location} ${clinicType}: Affordable ${service} Revealed`,
      primary_text: `You thought ${service} was only for the wealthy. You assumed it would cost a fortune. But our ${clinicType} in ${location} is changing that. We believe everyone deserves access to quality care — without the luxury price tag. ${offer}. Don't miss this opportunity.`,
      image_prompt: `News-style graphic with bold headline, ${clinicType} exterior, price comparison visual, clean professional layout, emerald and white color scheme`,
      hook: `${service} doesn't have to break the bank`,
      category: "Avatar Test B",
    },
    {
      id: 12,
      avatar: "Budget-Conscious Seeker",
      emotion: "hope",
      style: "Direct Offer",
      headline: `Premium ${service} At A Price You'll Love`,
      primary_text: `Great ${service} shouldn't require a second mortgage. At our ${clinicType} in ${location}, you get premium care, experienced providers, and real results — all at a price that makes sense. No hidden fees. No surprises. Just great value. ${offer}. Book now and save.`,
      image_prompt: `Clean value-focused design, happy diverse patients, ${clinicType} interior, warm inviting atmosphere, professional but approachable, lifestyle photography`,
      hook: "Premium results, honest pricing",
      category: "Style Test",
    },
    {
      id: 13,
      avatar: "Busy Professional",
      emotion: "curiosity",
      style: "Educational",
      headline: `5 Things To Know Before Your First ${service}`,
      primary_text: `Thinking about ${service}? You're not alone. But before you book, there are 5 things every first-timer should know. Our ${clinicType} in ${location} put together this quick guide so you can walk in with complete confidence. Knowledge is power. ${offer}. Read this first.`,
      image_prompt: `Clean educational layout, numbered list visual, modern ${clinicType} setting, professional doctor or practitioner, soft professional lighting, trust-building composition`,
      hook: "Read this before your appointment",
      category: "Style Test",
    },
    {
      id: 14,
      avatar: "Aging Gracefully Seeker",
      emotion: "fear",
      style: "Pattern Interrupt",
      headline: `The ${service} Mistake Most People Make`,
      primary_text: `Here's what nobody tells you about ${service}: choosing the wrong provider can cost you more than money. It can cost you confidence. At our ${clinicType} in ${location}, your safety and satisfaction come first. Every time. ${offer}. Choose the provider your face deserves.`,
      image_prompt: `Dramatic before/after comparison, professional medical setting, certified provider showing credentials, serious but caring expression, clinical but warm lighting`,
      hook: "Don't make this costly mistake",
      category: "Emotion Test",
    },
    {
      id: 15,
      avatar: "Health-Conscious Executive",
      emotion: "trust",
      style: "Testimonial",
      headline: `"Best ${clinicType} Decision I Ever Made"`,
      primary_text: `When a busy executive walks through our doors, they expect excellence. And that's exactly what they get. Our ${clinicType} in ${location} delivers world-class ${service} with the discretion and professionalism you demand. ${offer}. Read our reviews and see for yourself.`,
      image_prompt: `Five-star review montage, luxury ${clinicType} reception area, professional warm welcome, executive client testimonial feel, polished editorial style`,
      hook: "Rated #1 by ${location} executives",
      category: "Emotion Test",
    },
    {
      id: 16,
      avatar: "New Mom",
      emotion: "frustration",
      style: "Before/After",
      headline: `Your Post-Baby Body Deserves ${service}`,
      primary_text: `You love being a mom. But some days, you barely recognize the person in the mirror. That's okay — and it's fixable. ${service} at our ${clinicType} in ${location} helps moms feel confident in their own skin again. No judgment. Just results. ${offer}. You've earned this.`,
      image_prompt: `Authentic mom transformation, warm emotional photography, before and after subtle comparison, ${clinicType} caring environment, soft natural light`,
      hook: "Your body, your comeback story",
      category: "Emotion Test",
    },
    {
      id: 17,
      avatar: "Social Media Millennial",
      emotion: "empowerment",
      style: "Social Proof",
      headline: `${location}'s Most-Tagged ${clinicType} On Instagram`,
      primary_text: `There's a reason everyone's posting about us. Our ${service} results speak for themselves — and so do our patients. Join the thousands who've transformed their look at the most talked-about ${clinicType} in ${location}. ${offer}. Get your own transformation story.`,
      image_prompt: `Instagram feed collage, multiple happy patients, social media aesthetic, user-generated content feel, vibrant filters, ${clinicType} branded`,
      hook: "Join the #GlowUp movement",
      category: "Style Test",
    },
    {
      id: 18,
      avatar: "Budget-Conscious Seeker",
      emotion: "urgency",
      style: "Breaking News",
      headline: `Flash Sale: ${service} At ${clinicType} In ${location}`,
      primary_text: `This doesn't happen often. Our ${clinicType} in ${location} is running a limited flash sale on ${service}. Once the spots are gone, they're gone. You've been waiting for the right moment — this is it. ${offer}. Grab your spot before it's too late.`,
      image_prompt: `Flash sale announcement graphic, bold urgent typography, countdown element, ${clinicType} branded, emerald and gold color scheme, premium but accessible feel`,
      hook: "48-hour flash sale starts now",
      category: "Style Test",
    },
  ];
}
